<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomerIdentityService.Core\CustomerIdentityService.Core.csproj" />
    <ProjectReference Include="..\CustomerIdentityService.Infrastructure\CustomerIdentityService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Helpers\" />
  </ItemGroup>

</Project>
